### PR TITLE
Travis: install Bundler to get a green build

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR tries to fix the build on 1.9.3 by avoiding a very-old Bundler.

### CODE REVIEW

**Comment by jcoyne** [comment]
@apotonick How about a review of this PR?  Are you still intending to maintain this gem?

**Comment by jcoyne** [comment]
@apotonick Do you have a moment to review this PR?

**Comment by apotonick** [comment]
Actually, if you're interested in taking over this gem, just let me know. :beers:

**Comment by jcoyne** [comment]
@apotonick I'd be happy to take over if you want to add me to the rubygems owners.

**Pull request merged**
